# Generated by Django 4.2.23 on 2025-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(unique=True, verbose_name='Цитата')),
                ('weight', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, verbose_name='Вес')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100, verbose_name='Название источника')),
                ('type', models.CharField(choices=[('film', 'Фильм'), ('book', 'Книга'), ('song', 'Песня'), ('serial', 'Сериал'), ('life', 'Из жизни')], max_length=20, verbose_name='Тип')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Цитату',
                'verbose_name_plural': 'Цитаты',
                'db_table': 'quotes',
            },
        ),
    ]
