# Generated by Django 4.2.23 on 2025-08-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='weight',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='quotesources',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
